version: '3.7'

services:

  app:
    build: .
    volumes:
      - .:/app:rw
      - vendor:/app/vendor:rw
    working_dir: /app
    environment:
      PHPFPM_CONFIG: |
        [www]
        user = root
        group = root
    command:
      - sh
      - -xc
      - |
        if [ ! -e vendor/autoload.php ]; then
          composer install --prefer-dist --optimize-autoloader --ignore-platform-reqs
        fi
        echo "$$PHPFPM_CONFIG" > /usr/local/etc/php-fpm.d/zz-misc.conf
        exec php-fpm --allow-to-run-as-root --nodaemonize \
          -d error_reporting=-1 \
          -d display_errors=on \
          -d display_startup_errors=on \
          -d log_errors=on \
          -d error_log= \
          -d zend.assertions=1 \
          -d assert.exception=1 \
          -d date.timezone=Asia/Tokyo

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 9876:9876
    volumes:
      - .:/app:ro
    environment:
      NGINX_CONFIG: |
        upstream app {
          server app:9000;
        }
        server {
          listen 9876 default;
          charset utf-8;
          root /app/public/;
          try_files $$uri @app;
          location @app {
            fastcgi_pass app;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $$document_root/index.php;
          }
          location = /index.php {
            return 404;
          }
        }
    command:
      - sh
      - -xc
      - |
        echo "$$NGINX_CONFIG" >/etc/nginx/conf.d/default.conf
        exec nginx -g "daemon off;"

  xhgui:
    image: edyan/xhgui
    ports:
      - 8142:80

volumes:
  vendor:
